### ISSUE TITLE
Traits based GUI

### ISSUE THREAD

**Issue by rhaschke** [ubi-agni/stack_of_tasks#17]
I collect some ideas for a traits-based GUI here. Before implementing this in the final GUI, we should test these ideas on a toy example first.

- Each class offering editable properties should expose those properties as a `List[Tuple[str, Type]]`. Lists (in contrast to dicts) allow inserting new items at a custom position. A method assembling the GUI would then iterate over that _ordered_ list and populate a QFormLayout (as you do now) or a `PropertyModel`. A signal/slot mechanism should take care of insertions/removals from that list to update an open GUI appropriately!
- A `DelegateFactory` and/or `EditorFactory` create `QItemDelegates` and `QWidgets` to display/edit an item. (QItemDelegate provides a `createEditor()` method).
  By default, an item's `str()` representation could be displayed (in a `TreeView`). Also, meaningful default editors for standard types should be provided. The defaults could be changed by registering a different factory method for a specific (or new) type.
- Editors (and delegates?) should be _customizable_ for each item. Think of multiple `str` items, that should be edited with different custom editors, e.g. a `QLineEdit` _or_ `QComboBox` allowing item-specific completion/validation. To this end, we could use a wrapper class similar to pyqtgraph's [`Parameter`](https://pyqtgraph.readthedocs.io/en/latest/api_reference/parametertree/parameter.html#pyqtgraph.parametertree.Parameter) class (or [`ParameterItem`](https://pyqtgraph.readthedocs.io/en/latest/api_reference/parametertree/parameteritem.html)?). This wrapper would explicitly specify meta properties, like the delegate/editor factory method, min/max/step values for an int or float, a default value, the name, etc.
- Validation should be handled by the Property as well, e.g. via an optional `validate()` method. To validate for interdependencies, e.g. `RelativeTask` should have at least one `JointFrame` reference, the property could call its parent's `validate()` method.

**Comment by rhaschke** [comment]
> Ich würde nur auf eine starke Trennung zwischen `Property` und UI Wert legen, damit ein Controller auch komplett ohne Qt lauffähig ist.

Eine Trennung zwischen Property und UI ist auf jeden Fall sinnvoll. Die Frage ist, wie _"komplett"_ man auf Qt verzichten kann/will. `Property` von QObject abzuleiten, um Qt's signal-slot-Mechanismus für Updates in beide Richtungen verwenden zu können, würde - glaube ich - die Implementation etwas (oder sehr viel?) einfacher machen. Man bräuchte dann `QtCore`, könnte aber natürlich das Programm komplett ohne GUI und Qt event loop laufen lassen (weil in diesem Fall keine signals verarbeitet werden müssten).

Grundsätzlich muss man Updates ja in beiden Richtungen kommunizieren: Property <-> GUI
- GUI -> Property ist einfach: Die GUI emitted signals, die einfach an eine Funktion (z.B. auch lambda) connected werden, die dann den Wert updaten.
- Property -> GUI ist ohne signals viel komplizierter: Man bräuchte callbacks, die bei Änderungen des Wertes, die entsprechenden GUI-Elemente benachrichtigen.

[traisui](https://docs.enthought.com/traitsui/#traitsui-traits-capable-windowing-framework) verwendet ja folgende Syntax:
```python
from traits.api import HasTraits, Str, Range, Enum
class Person(HasTraits):
    # declare properties
    name = Str('Jane Doe')
    age = Range(low=0)
    gender = Enum('female', 'male')

person = Person(age=30) # instantiate the class
person.age = 42 # access elements as usual
```

Die `HasTraits` Basisklasse sorgt dafür:
- dass automatisch ein Konstruktor angelegt wird, der alle deklarierten `HasTraits`-Elemente der Klasse akzeptiert
- vermutlich entsprechende python properties angelegt werden (mit gettern und settern), so dass die setter entsprechende callbacks absetzen können. Die TraitsUI "weiss", wo/wie sie sich bei diesen callbacks registrieren kann, um über value-updates informiert zu werden.

Vielleicht könntest Du diese `traits.api` einfach verwenden, aber `traitsui` durch Qt ersetzen? Du müsstest dann "lediglich" herausbekommen, wie Du Dich an den callbacks anmelden kannst.

Alternativ schwebte mir so eine Syntax vor:
```python
from enum import Enum
class Gender(Enum):
    female = 1
    male = 2

class Person(Property):
    # declare properties
    __traits__ = dict(name='Jane Doe', age=RangeProperty(42, low=0), gender=Gender.female)

person = Person(age=30) # instantiate the class
person.age = 42 # access elements as usual
# allow insertion and removal of properties at run time:
person.__traits__.insert(address=AddressProperty(...)
```
Hier könnte man properties on-the-fly hinzufügen und entfernen. Außerdem muss man Standardtypen nicht mit den Traits-Klassen deklarieren (könnte man aber, um z.B. wie oben den erlaubten Range zu übergeben).

**Comment by felixkol** [comment]
Ich habe mir nun traits lange und ausführlich angeschaut. An sich ist die library sehr mächtig und ermöglicht viele spannende und nützliche Dinge, die auch wir hier perfekt einbauen könn(t)en. Allerdings wird auch eine komplett neue Abstraktions- und damit Komplexitätsebene aufgemacht. Wir müssten im Prinzip den kompletten Code einmal dahin gehend umformulieren. 

Schwieriger wird es dann sowieso bei der UI. Es gibt `traitsui`, das ermöglicht Editoren für `HasTrait`-Klassen. Diese kann ich aber nicht in eine bereits existierende QT Gui einbinden. Es gibt noch die library `qt-binders`, die `widget`-Klassen mit traits versieht. Allerdings habe ich das nicht wirklich zum laufen bekommen. 

Ich hoffe noch eine Möglichkeit in der Doku zu entdecken, traits mit halbwegs wenig Aufwand in QT einzubetten, ohne ein komplett anderes System zu verwenden.

Der letzte und für uns bisher einzig machbare Weg, den ich sehe, ist die bisherige UI zu nehmen und beide Richtungen des Datenflusses manuell zu machen. 

Traits bietet die Möglichkeit von observe, ein callback, wenn sich ein trait ändert. Um in deinem Beispiel zu bleiben:
```python
class Person(HasTraits):
    # declare properties
    name = Str('Jane Doe')
    age = Range(low=0)
    gender = Enum('female', 'male')

p = Person()
p.observe(print, 'age') 
p.age = 42

# change event for p.age is emitted
```

So könnte man jedes observe dazu nutzen, die Daten in der UI zu updaten. 
Die andere Richtung wäre, wie du schon sagtest, wäre dann `qtSignal` -> `lambda `-> `trait_set`.

Die Validation wird auch von traits selbst gemanaged. Im `Range`-trait gibt es Möglichkeit offene Intervalle zu definieren, etwas dass z.B. für das `weight` in Tasks sinnvoll wäre.  Da aber die `QDoubleSpinBox` keine offenen Intervalle zulässt, müsste hier nicht nur der user-input durch Text sondern auch scrolling und buttons gechecked werden.

**Comment by rhaschke** [comment]
> Allerdings wird auch eine komplett neue Abstraktions- und damit Komplexitätsebene aufgemacht. Wir müssten im Prinzip den kompletten Code einmal dahin gehend umformulieren.

Was genau meinst Du damit? Dass wir alles auf die `traits`-Typen umstellen müsen, also z.B.  `str` ➔ `Str`? Das hatte ich oben ja auch schon angemerkt. Oder gibt es noch eine andere Abstraktionsebene?

> `traitsui` ermöglicht Editoren für `HasTrait`-Klassen. Diese kann ich aber nicht in eine bereits existierende QT Gui einbinden.

Ja, das Problem ist hier, dass `traitsui` bewusst framework-agnostisch gehalten wurde (also mit Qt, wxwidgets, usw. verwendet werden kann). Daher kommt man nicht so einfach an die PyQt widgets heran.

> ... traits mit halbwegs wenig Aufwand in QT einzubetten, ohne ein komplett anderes System zu verwenden.

Den Weg hast Du ja schon skiziiert:

> So könnte man jedes `observe` dazu nutzen, die Daten in der UI zu updaten.
> Die andere Richtung wäre, wie du schon sagtest, wäre dann `qtSignal` -> `lambda `-> `trait_set`.

oder ist das für Dich schon der manuelle Weg:

> Der letzte und für uns bisher einzig machbare Weg, ist die bisherige UI zu nehmen und beide Richtungen des Datenflusses manuell zu machen.

Hast Du das beispielhaft mal mit einem `Trait` und einem `QWidget` probiert?

**Comment by felixkol** [comment]
Ich habe jetzt ein Beispiel für `traits` und `qt` erstellt und einen [Branch](https://github.com/ubi-agni/stack_of_tasks/tree/dev-traits-based-ui) für traits erstellt.

Als Anzeigelement habe ich mich an einer `QDoubleSpinbox` versucht, da diese etwas komplexer als nur eine reine Eingabe ist und sich relativ gut, die zusätzliche Komplexität zeigt, die ich meinte. Der Datenfluss von Datenklasse zu UI ist, wie oben schon beschrieben eben `observe` und `qtSignal`, also der 'manuelle' weg. 

Im Beispiel besteht bis jetzt nur die Möglichkeit, einen `Range`-`trait` an die Spinbox zu binden. Die Eingabe auf UI-Seite wird validiert, ohne Sonderfälle, wie strings die mit einem Minus starten etc. 

Theoretisch gibt es in traits auch die Möglichkeit, `trait`-Eigenschaften an andere `traits` zu binden, z.B. die untere Schranke von `Range` an einen `Float` trait. Theoretisch muss also für jede dieser Eigenschaften geschaut werden, ob sie statisch ist, falls nein mit `observe` die UI dem entsprechend geändert werden.  
Jetzt ist die Frage, ob es sich lohnt, jedes Widget, das wir Nutzen wollen `trait`-Tauglich zu machen. Dazu kommen noch das `ListModel` für `List`-`traits`. 

Einen großen Teil davon könnte `qt_binder` erledigen, ich versuche da gerade noch hinter zu kommen, da das noch in früher Entwicklung ist. 

Die Frage, die ich mir gerade stelle ist, ob es sich lohnt, unsere gesamte Logik so zu ändern, dass der Datenfluss mit `traits` stattfindet, und zusätzlich die UI mit `traits` zu erweitern, oder ob da Zeitaufwand und Nutzen nicht im Verhältnis stehen.

**Comment by felixkol** [comment]
In 3fd1a8b6db53b250ea71f557e3e83fcd0234137d habe ich qt_binder nun zum Laufen bekommen. Damit können wir unsere UI relativ einfach weiter verwenden, es gibt sogar die Möglichkeit [ui-files zu laden](https://qt-binder.readthedocs.io/en/latest/api/widgets.html#qt_binder.widgets.UIFile)! Einiges muss noch angepasst werden, aber ich denke, das ist sehr gut machbar. 
Wenn nichts dagegen spricht, würde ich mich daran machen, den Code nach und nach anzupassen.

**Comment by rhaschke** [comment]
Sehr gut. Bevor Du den Code umstellst, solltest Du noch schauen, inwieweit Du die Erstellung der GUI selbst, automatisieren kannst. Meine ursprüngliche Idee war ja, einfach die Liste aller traits (rekursiv) durchzugehen und dafür das "geeignete" QWidget (oder jetzt qt_binder widget) zu erzeugen.

Ansonsten musst Du für jede Änderung der traits / jeden neuen Task neuen Code schreiben, um die zugehörige Config GUI zu erzeugen.

**Comment by felixkol** [comment]
Da überlege ich mir noch was. Theoretisch reicht ja ein mapping von trait-type zu widget, vielleicht mit der Möglichkeit dieses mapping für manche Klasse zu überschreiben, falls z.B. ein `Range` in einem bestimmten Fall nicht als `Spinbox` sonder als `Slider` dargestellt werden soll.

**Comment by felixkol** [comment]
Marker und Marker-Server als `traits` implementiert. Theoretisch kann man noch weitere marker parameter einrichten, aber die Grundlagen sind da, zusammen mit einem Beispiel in `scripts/dev_traits/rebuild.py`. 

Mir ist aufgefallen, dass der `Array`-`trait` nur bei wirklichen Zuweisungen des Attributs funktioniert, nicht aber wenn man das Array via slices verändert. Das ist doof. Da muss man vielleicht manuell updates triggern, wenn man etwas an einem Object verändert (auf wenn wir das gerade vermeiden wollten... ich lasse mir was einfallen.)

**Comment by felixkol** [comment]
In cfaf24bc01cf8219241139c10ed5dc917d2b7408 habe ich Refs auf traits umgestellt, davon können nun alle Subklasse für Refs abgeleitet werden. 
Außerdem mein Ansatz für tasks mit traits. Mein großes Problem ist, dass sich `Property`-traits mit dem vorhandenen `observer`-pattern scheinbar nicht dynamisch erstellen lassen - zumindest bekomme ich es nicht hin, die Doku ist auch so gar nicht hilfreich. Das brauche ich aber, um `compute` je nach Task-Typ triggern zu lassen. Eine `Relative`-Task triggert bei `ref.T`, `ref.J` - changes, eine z.b. `JointPose` bei Änderung der gewünschten Gelenkwinkel.

Am `RobotModel` arbeite ich gerade noch, da die selben Fragen für geklärt sein müssen.
