### ISSUE TITLE
Inconsistent handling of task weights

### ISSUE THREAD

**Issue by rhaschke** [ubi-agni/stack_of_tasks#21]
Hi @felixkol,

Skimming through your code, I noticed that some tasks seem to use the weighting factor twice: As far as I understand, this piece of code applies the weight to _all_ components returned by `compute()` for _any_ task already:
https://github.com/ubi-agni/stack_of_tasks/blob/97e191a72a0fa379da8315c00f4eff7877f64fd8/python/stack_of_tasks/tasks/Task.py#L99-L101

However, in specific tasks you inconsistently apply the weight factor again, e.g. in `PositionTask` only for the error:
https://github.com/ubi-agni/stack_of_tasks/blob/97e191a72a0fa379da8315c00f4eff7877f64fd8/python/stack_of_tasks/tasks/Eq_Tasks.py#L15
... and in the `OrientationTask` only for the Jacobian:
https://github.com/ubi-agni/stack_of_tasks/blob/97e191a72a0fa379da8315c00f4eff7877f64fd8/python/stack_of_tasks/tasks/Eq_Tasks.py#L27

This might explain the weird convergence behavior you have seen...

**Comment by felixkol** [comment]
Good catch! Missed that. 

Fixed in 150a3ef14a39219dfbb63bd6e1873b4f6362c359

**Comment by rhaschke** [comment]
Did that solve the weird convergence behavior between linear and quadratic softness?
